/*
Create Database
*/

CREATE DATABASE `movies_app`;


/*
Create table
*/
DROP TABLE IF EXISTS `movies_app`.`movie_details`;
CREATE TABLE  `movies_app`.`movie_details` (
  `movie_id` int(11) NOT NULL AUTO_INCREMENT,
  `movie_name` varchar(500) DEFAULT NULL,
  `has_won_oscar` tinyint(1) DEFAULT NULL,
  `theatre_gross` double DEFAULT NULL,
  `average_rating` float DEFAULT NULL,
  `created` date DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `imdb_id` varchar(50) NOT NULL,
  `total_ratings` int(11) NOT NULL DEFAULT 0,
  `poster` varchar(500) NOT NULL,
  PRIMARY KEY (`movie_id`)
) ENGINE=InnoDB AUTO_INCREMENT=486 DEFAULT CHARSET=utf8mb4;


/*
Insert all movie details
*/

insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Black Swan', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Fighter', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Inception', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Kids Are All Right', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The King's Speech', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('127 Hours', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Social Network', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Toy Story 3', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('True Grit', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Winter's Bone', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Avatar', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Blind Side', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('District 9', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('An Education', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Hurt Locker', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Inglourious Basterds', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Precious: Based on the Novel 'Push' by Sapphire', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Serious Man', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Up', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Up in the Air', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Curious Case of Benjamin Button', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Frost/Nixon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Milk', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Reader', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Slumdog Millionaire', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Atonement', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Juno', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Michael Clayton', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('No Country for Old Men', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('There Will Be Blood', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Babel', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Departed', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Letters from Iwo Jima', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Little Miss Sunshine', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Queen', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Brokeback Mountain', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Capote', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Crash', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Good Night, and Good Luck.', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Munich', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Aviator', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Finding Neverland', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Million Dollar Baby', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ray', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sideways', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lord of the Rings: The Return of the King', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lost in Translation', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Master and Commander: The Far Side of the World', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mystic River', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Seabiscuit', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Chicago', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gangs of New York', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Hours', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lord of the Rings: The Two Towers', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Pianist', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Beautiful Mind', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gosford Park', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('In the Bedroom', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lord of the Rings: The Fellowship of the Ring', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Moulin Rouge', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Chocolat', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Crouching Tiger, Hidden Dragon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Erin Brockovich', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gladiator', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Traffic', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('American Beauty', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Cider House Rules', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Green Mile', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Insider', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Sixth Sense', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Elizabeth', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Life Is Beautiful', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Saving Private Ryan', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Shakespeare in Love', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Thin Red Line', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('As Good as It Gets', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Full Monty', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Good Will Hunting', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('L.A. Confidential', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Titanic', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The English Patient', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fargo', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Jerry Maguire', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Secrets & Lies', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Shine', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Apollo 13', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Babe', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Braveheart', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Postman (Il Postino)', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sense and Sensibility', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Forrest Gump', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Four Weddings and a Funeral', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Pulp Fiction', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Quiz Show', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Shawshank Redemption', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Fugitive', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('In the Name of the Father', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Piano', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Remains of the Day', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Schindler's List', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Crying Game', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Few Good Men', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Howards End', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Scent of a Woman', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Unforgiven', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Beauty and the Beast', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Bugsy', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('JFK', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Prince of Tides', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Silence of the Lambs', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Awakenings', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dances With Wolves', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ghost', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Godfather, Part III', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Good Fellas', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Born on the Fourth of July', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dead Poets Society', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Driving Miss Daisy', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Field of Dreams', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('My Left Foot', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Accidental Tourist', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dangerous Liaisons', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mississippi Burning', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Rain Man', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Working Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Broadcast News', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fatal Attraction', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Hope and Glory', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Last Emperor', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Moonstruck', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Children of a Lesser God', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Hannah and Her Sisters', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Mission', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Platoon', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Room with a View', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Color Purple', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Kiss of the Spider Woman', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Out of Africa', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Prizzi's Honor', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Witness', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Amadeus', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Killing Fields', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Passage to India', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Places in the Heart', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Soldier's Story', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Big Chill', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Dresser', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Right Stuff', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Tender Mercies', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Terms of Endearment', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('E.T. The Extra-Terrestrial', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gandhi', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Missing', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Tootsie', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Verdict', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Atlantic City', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Chariots of Fire', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('On Golden Pond', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Raiders of the Lost Ark', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Reds', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Coal Miner's Daughter', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Elephant Man', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ordinary People', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Raging Bull', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Tess', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All That Jazz', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Apocalypse Now', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Breaking Away', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Kramer vs. Kramer', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Norma Rae', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Coming Home', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Deer Hunter', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Heaven Can Wait', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Midnight Express', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('An Unmarried Woman', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Annie Hall', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Goodbye Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Julia', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Star Wars', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Turning Point', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All the President's Men', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Bound for Glory', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Network', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Rocky', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Taxi Driver', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Barry Lyndon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dog Day Afternoon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Jaws', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Nashville', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('One Flew over the Cuckoo's Nest', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Chinatown', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Conversation', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Godfather Part II', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lenny', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Towering Inferno', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('American Graffiti', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cries and Whispers', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Exorcist', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Sting', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Touch of Class', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cabaret', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Deliverance', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Emigrants', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Godfather', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sounder', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Clockwork Orange', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fiddler on the Roof', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The French Connection', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Last Picture Show', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Nicholas and Alexandra', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Airport', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Five Easy Pieces', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Love Story', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('M*A*S*H', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Patton', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Anne of the Thousand Days', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Butch Cassidy and the Sundance Kid', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Hello, Dolly!', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Midnight Cowboy', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Z', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Funny Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lion in Winter', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Oliver!', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Rachel, Rachel', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Romeo and Juliet', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Bonnie and Clyde', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Doctor Dolittle', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Graduate', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Guess Who's Coming to Dinner', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('In the Heat of the Night', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Alfie', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Man for All Seasons', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Russians Are Coming The Russians Are Coming', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Sand Pebbles', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Who's Afraid of Virginia Woolf?', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Darling', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Doctor Zhivago', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ship of Fools', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Sound of Music', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Thousand Clowns', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Becket', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mary Poppins', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('My Fair Lady', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Zorba the Greek', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('America America', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cleopatra', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('How the West Was Won', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lilies of the Field', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Tom Jones', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lawrence of Arabia', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Longest Day', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Meredith Willson's The Music Man', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mutiny on the Bounty', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('To Kill a Mockingbird', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fanny', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Guns of Navarone', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Hustler', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Judgment at Nuremberg', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('West Side Story', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Alamo', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Apartment', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Elmer Gantry', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sons and Lovers', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Sundowners', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Anatomy of a Murder', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ben-Hur', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Diary of Anne Frank', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Nun's Story', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Room at the Top', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Auntie Mame', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cat on a Hot Tin Roof', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Defiant Ones', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gigi', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Separate Tables', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Bridge on the River Kwai', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Peyton Place', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sayonara', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('12 Angry Men', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Witness for the Prosecution', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Around the World in 80 Days', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Friendly Persuasion', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Giant', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The King and I', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Ten Commandments', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Love Is a Many-Splendored Thing', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Marty', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mister Roberts', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Picnic', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Rose Tattoo', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Caine Mutiny', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Country Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('On the Waterfront', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Seven Brides for Seven Brothers', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Three Coins in the Fountain', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('From Here to Eternity', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Julius Caesar', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Robe', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Roman Holiday', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Shane', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Greatest Show on Earth', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('High Noon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ivanhoe', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Moulin Rouge', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Quiet Man', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('An American in Paris', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Decision before Dawn', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Place in the Sun', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Quo Vadis', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Streetcar Named Desire', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All about Eve', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Born Yesterday', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Father of the Bride', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('King Solomon's Mines', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sunset Blvd.', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All the King's Men', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Battleground', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Heiress', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Letter to Three Wives', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Twelve O'Clock High', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Hamlet', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Johnny Belinda', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Red Shoes', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Snake Pit', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Treasure of the Sierra Madre', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Bishop's Wife', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Crossfire', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gentleman's Agreement', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Great Expectations', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Miracle on 34th Street', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Best Years of Our Lives', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Henry V', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('It's a Wonderful Life', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Razor's Edge', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Yearling', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Anchors Aweigh', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Bells of St. Mary's', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lost Weekend', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mildred Pierce', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Spellbound', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Double Indemnity', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gaslight', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Going My Way', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Since You Went Away', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Wilson', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Casablanca', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('For Whom the Bell Tolls', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Heaven Can Wait', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Human Comedy', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('In Which We Serve', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Madame Curie', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The More the Merrier', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Ox-Bow Incident', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Song of Bernadette', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Watch on the Rhine', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Invaders', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Kings Row', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Magnificent Ambersons', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mrs. Miniver', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Pied Piper', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Pride of the Yankees', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Random Harvest', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Talk of the Town', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Wake Island', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Yankee Doodle Dandy', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Blossoms in the Dust', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Citizen Kane', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Here Comes Mr. Jordan', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Hold Back the Dawn', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('How Green Was My Valley', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Little Foxes', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Maltese Falcon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('One Foot in Heaven', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Sergeant York', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Suspicion', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All This, and Heaven Too', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Foreign Correspondent', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Grapes of Wrath', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Great Dictator', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Kitty Foyle', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Letter', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Long Voyage Home', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Our Town', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Philadelphia Story', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Rebecca', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dark Victory', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Gone with the Wind', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Goodbye, Mr. Chips', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Love Affair', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mr. Smith Goes to Washington', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ninotchka', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Of Mice and Men', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Stagecoach', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Wizard of Oz', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Wuthering Heights', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Adventures of Robin Hood', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Alexander's Ragtime Band', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Boys Town', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Citadel', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Four Daughters', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Grand Illusion', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Jezebel', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Pygmalion', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Test Pilot', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('You Can't Take It with You', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Awful Truth', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Captains Courageous', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dead End', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Good Earth', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('In Old Chicago', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Life of Emile Zola', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lost Horizon', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('One Hundred Men and a Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Stage Door', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Star Is Born', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Anthony Adverse', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Dodsworth', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Great Ziegfeld', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Libeled Lady', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mr. Deeds Goes to Town', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Romeo and Juliet', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('San Francisco', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Story of Louis Pasteur', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Tale of Two Cities', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Three Smart Girls', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Alice Adams', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Broadway Melody of 1936', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Captain Blood', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('David Copperfield', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Informer', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Les Miserables', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Lives of a Bengal Lancer', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Midsummer Night's Dream', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Mutiny on the Bounty', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Naughty Marietta', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Ruggles of Red Gap', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Top Hat', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Barretts of Wimpole Street', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cleopatra', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Flirtation Walk', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Gay Divorcee', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Here Comes the Navy', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The House of Rothschild', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Imitation of Life', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('It Happened One Night', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('One Night of Love', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Thin Man', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Viva Villa!', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The White Parade', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cavalcade', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('A Farewell to Arms', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('42nd Street', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('I Am a Fugitive from a Chain Gang', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Lady for a Day', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Little Women', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Private Life of Henry VIII', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('She Done Him Wrong', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Smilin' Through', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('State Fair', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Arrowsmith', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Bad Girl', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Champ', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Five Star Final', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Grand Hotel', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('One Hour with You', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Shanghai Express', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Smiling Lieutenant', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Cimarron', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('East Lynne', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Front Page', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Skippy', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Trader Horn', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('All Quiet on the Western Front', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Big House', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Disraeli', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Divorcee', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Love Parade', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Feature Productions', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fox', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Metro-Goldwyn-Mayer', YES, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Metro-Goldwyn-Mayer', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Paramount Famous Lasky', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('The Caddo Company', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Fox', NO, 0, 0, sysdate, 0);
insert into movie_details (movie_name, has_won_oscar, theatre_gross, average_rating, created, is_deleted) value ('Paramount Famous Lasky', YES, 0, 0, sysdate, 0);
